version: "1.0"
services:
  back-end:
    build: ./probe/
    container_name: probe
    ports:
      - "8080:8080"
    env_file:
      - 'probe.env'
    depends_on:
      - database
      
  database:
    image: postgres:14-alpine
    container_name: probe-db
    ports:
      - "5432:5432"
    env_file:
      - 'probe.env'

volumes:
  volumes: